export const ImageInfos = [
  {
    image: "../assets/models/model4.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
  {
    image: "../assets/models/model3.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
  {
    image: "../assets/models/model4.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
  {
    image: "../assets/models/model1.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
  {
    image: "../assets/models/model2.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
  {
    image: "../assets/models/model3.png",
    label: "Orange XL",
    title: "title",
    group: "OrangPunk",
    viewedNumber: 12000,
    likedNumber: 12000,
  },
];
